name: ${PROJECT_CODE}
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    env_file: .env
    container_name: php_${PROJECT_CODE}
    volumes:
      - ./.composer-docker/cache:/root/.composer/cache:delegated
      - ${PROJECT_ROOT_DIR}:${SERVER_ROOT_DIR}
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./apache/sites-enabled/custom-vhost.conf:/etc/apache2/sites-enabled/custom-vhost.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=docker
    ports:
      - '80:80'
    networks:
      - my-network
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    env_file: .env
    container_name: phpmyadmin_${PROJECT_CODE}
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - my-network
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    env_file: .env
    container_name: db_${PROJECT_CODE}
    restart: unless-stopped
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_storage:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - my-network
      
volumes:
  vendor_directory_storage:
    name: vendor_directory_storage_${PROJECT_CODE}
  db_storage:
    name: db_storage_${PROJECT_CODE}
  esdata:

networks:
  my-network:
    driver: bridge
    